### PR TITLE
24 feat input validation required fields and angles

### LINKED ISSUE #24: Feat: Input validation required fields and angles
- [x] Implement a check that fields marked 'required' on the spreadsheet have values. This check should be non-blocking and just add a warning.
- [x] Add the limits on angles that we discussed on March 9th: Grazing True: 0-90, Grazing False: -14 to 90

### LINKED ISSUE #25: Bug: Spreadsheet load can skip lines 1-4 if bar and acquisitions sheets are mismatched
Spreadsheet load sometimes skips rows 1-4 even if sheet has no documentation rows.
 
 This is a problem because if you try to input a sheet that was automatically output, you lose the first few acquisitions.
 This bug is fixed in a pull request I'm about to make. Just documenting it here in case someone else runs into it.

### PR DESCRIPTION
**Pull request by BijalBPatel**
This requests implements #24 and fixes #25

- [x] spreadsheets.py -> load_samplesxlsx() now inspects the excel sheet to see if it has metadata rows (and how many). If it does, these are marked to be skipped for importing data. They are also used to determine what 'bar' and 'acquisitions' parameters are marked REQUIRED
- [x] spreadsheets.py -> load_samplesxlsx() now checks whether REQUIRED 'bar' and 'acquisitions' parameters have input values and raises an error if not.
- [x] spreadsheets.py -> isParamValid() is a new function that abstracts some boilerplate for checking if a given value matches a set of allowed values or falls within an allowed/disallowed numerical interval
- [x] spreadsheets.py -> load_samplesxlsx() now has input validation on the 'bar'->angle and 'acquisitions'->angles parameter to be within the limits described on the spreadsheet. These give a warning if exceeded.
- [x] acquisition.py -> dryrun_bar has minor cleanup/ changes to what info is displayed 

Future suggestion: 

1. All of the 'recommended' parameter values from the spreadsheet instructions could be checked. This would be easier/ less error prone if specify upper and lower bounds along with the default values in 'defaults.py'. 

Discussion Point:
A quick note is that there are basically two places for input validation, in spreadsheets.py (when loading the sheet) and in acquisitions.py (dry run). 

I think this could be a good paradigm: weak ('policy') limits in load_samplesxlsx, hard ('instrumentation/physical') limits in dryrun_bar

So load_samplesxlsx():
- sanitizes inputs 
- Checks "Did you fill out the sheet correctly" (e.g., for empty cells, typos, etc.)
- Gives warnings about exceeding recommended parameter limits (e.g., keep angles between 0-90 even though its possible to go further out), 

dryrun_bar:
- Collects warnings and exceptions from instrumentation limits that are hard coded into the plans (e.g., cant go past -155 etc). 

It also could just get redundant and confusing - so let me know if I should just move angle validation over to dryrun_bar.

### CODE REVIEW

**Comment by EliotGann** [comment]
it seem like isParamValid() should handle errors a bit better.  I see that you are usually putting it in try:excepts which seems like something that it should be doing itself?

**Comment by EliotGann** [comment]
I think all of the validation parameters should be encoded as constants in default.py, not in the spreadsheet or hard coded.  like [{'parameter':'angle','type':[float,int],'limits':[-90,90]}]  at least for the first set of are they reasonable at all checks... more specific conditional checks (like, if grazing etc) can be hard coded.  perhaps https://pypi.org/project/schema/ is the right way to implement this...

**Comment by EliotGann** [comment]
I'm not loving these warnings everywhere whenever I open a bar that doesn't have the columns... that gets annoying when working at the beamline where none of the bars have that

**Comment by BijalBPatel** [comment]
Thats fair - they aren't needed at all if we are just pulling validation from the default.py

**Review by EliotGann — APPROVED** [review]
I think this is ready to merge.  I'll plan to do it later today unless anyone has any issues remaining

**Pull request merged**
