### PR TITLE
5 dryrun validation and documentation

### LINKED ISSUE #5: Dryrun Validation and Documentation
Opening and Issue to track changes from BP's 230107 testing

### PR DESCRIPTION
**Pull request by BijalBPatel**
Done for now  - a bit more validation of inputs to do, but seems pretty much ready to send out.

### CODE REVIEW

**Comment by BijalBPatel** [comment]
Fixed most things i saw - check the issues for the bigger changes/ ones i thought might need review.

**Comment by EliotGann** [comment]
Let me test it out on the beamline..  I would like to address the following before finishing it:

1. default NEXAFS detector behavior
2. default group behavior -> I think a quick chat to discuss your expectations would help me
3. I am thinking of one simplification to the structure of the "queue" level list.  why not group it to rather than the current [{acq_index:1,queue_index:1,acq_info(repeated),step_info}] -> [{acq_1_info,'steps': [{step_1_info},{step_2_info}] }] ... I think this will make the queue more complicated, but it's just adding in an extra for loop to un pack it all, and you retain the acq info for all of the steps, which is really ugly right now.  Maybe this should be a change after this merge now that I think about it

**Comment by EliotGann** [comment]
@BijalBPatel I believe the json dumps is doing what you mean in for displaying the acquisition details.  let me know if not.  As is, I believe everything is fine from my point of view.

**Comment by BijalBPatel** [comment]
Perfect!

**Pull request merged**
