### PR TITLE
17 sample bar template v2023 11 suggestions

### LINKED ISSUE #17: Sample_Bar_template_v2023_1.1 Suggestions
Suggestions for the next version of the spreadsheet based on testing 230121. All minor suggestions.

- On the "Acquisitions" Sheet, data validation for sample_id appears to be failing (I can put whatever I want and it doesn't care if it doesnt match a sample_id in the "Bar" sheet). This may get caught on dry-run. Not sure if you want it to be prevented within the excel sheet though.

-On the "Acquisitions" Sheet, suggested to change example for angles to [-10, 20,40,55,70,90] so that it makes clear how to get around excel's limitation for specifying negative values in a list. Similarly for polarization (or anywhere you might lead with a negative number in a list). May prevent emails from users.

- On the "Acquisitions" Sheet, suggested to declare default behavior for all cells. So that the 'example' cell either starts or ends with "Default: <default value> "

- On the "Acquisitions" Sheet, update the documentation on the "group" parameter "Rules" cell to match the new behavior. 

- On the "Acquisitions" Sheet, update the documentation on the "priority" parameter to mention that it is an option to specify priority each 'group' and not rank them globally.

### PR DESCRIPTION
**Pull request by BijalBPatel**
I think I'm at a stopping point on this. This PR will need a couple of manual changes before merging.

Summary of changes:

New spreadsheet template draft for review in the \example folder:  Sample_Bar_v2023_1.NIST.230301Draftv2_Clean.xlsx
- Revised documentation throughout
- Added default values identified by reading the source
- Added new columns to correspond to the autogenerated columns that are in the output excel sheets (to aid copy pasting flow)

Code changes:
- Added logic to handle empty autogenerated columns in the input sheet (Bar -> 'location', 'bar_loc', etc).
- Edited default sample dict to force output column order to match input template sheet, added some missing columns.
- Minor cleanup throughout

Need To-dos:
- [ ] Finalize spreadsheet and rename it/overwrite the one in the /example folder
- [ ] Generate new wiki tables from the new documentation and post on the wiki
- [ ] Upload the new spreadsheet template to the wiki

Nice to do:
- [ ] More rigorously test new spreadsheet loading and outputting [add real scans from last beamtime to the test acquisitions]

### CODE REVIEW

**Comment by EliotGann** [comment]
I made some suggestions when editing the wiki.  https://wiki-nsls2.bnl.gov/beamline7ID1/index.php?title=RSoXS_Samples&diff=453&oldid=371

**Comment by BijalBPatel** [comment]
> I made some suggestions when editing the wiki. https://wiki-nsls2.bnl.gov/beamline7ID1/index.php?title=RSoXS_Samples&diff=453&oldid=371

I'm not sure I follow - i had not updated the wiki documentation for the spreadsheet parameters yet, so the text to review/revise is still only in the excel file:

https://github.com/NSLS-II-SST/rsoxs_scans/blob/17-sample_bar_template_v2023_11-suggestions/example/Sample_Bar_v2023_1.NIST.230301Draftv2_Clean.xlsx

Did that stuff look good? Then we're ready to upload it to the wiki. But if you're working on the scheme to auto-populate the spreadsheet from defaults.py we can hold off until thats ready maybe.

**Comment by EliotGann** [comment]
Oh, well then ignore that.  I haven’t pulled that branch yet

**Comment by EliotGann** [comment]
I think we should remove all changes from this except just those to the spreadsheet.  all other changes are in the other pull request

**Pull request merged**
