### PR TITLE
Nested outputs

### PR DESCRIPTION
**Pull request by EliotGann**
changed the format of the output queue from dry_run to be a list of acquisitions, which have all of their information, and a "steps" entry which is the list of dictionaries with "action" and "description".  this makes handling the outputs a lot more handy.  I believe I've changed the way everything handles the output to compensate.

### CODE REVIEW

**Comment by EliotGann** [comment]
also, somewhat unrelatedly added in some basic spreadsheet validation on load, using the lists of configurations and edges

**Comment by BijalBPatel** [comment]
Skimmed through everything, and noticed just a couple quick things:

1. For Sample_Bar_template_v2023_1.0.xlsx, only thing i noticed is that the Rules for column 'group' in the 'Acquisitions' sheet need to be updated for the new behavior of group. (Cell D52 of SheetRulesAndMetaData). 

    Old Wording: 
    
    > string or number.  "all" or not specifying will mean this acquisition will run with any grouping.  Not specifying a group= in run_bar command will run all samples no matter their group
    
    Proposed Wording:
    
    > string or number.  "all" means this acquisition will run with any grouping.  Not specifying a group= in run_bar command will run all samples no matter their group
    
    You could also add more suggested examples, if you want to push this for experiment planning e.g., "BBP_BCPSet1", "Liquid_NCNR_BioSet1")

2. Did we implement validation of sheet version anywhere? So that dry-run of sheets that are invalid this cycle fails (or at least warns?)

      - Suggested implementation: Add a list of valid spreadsheet versions to defaults.py and compare against it at the start of either spreadsheets.load_samplesxlsx or acquisition.dryrun_bar. 
      
      This code in spreadsheets.convertSampleSheetExcelMediaWiki() extracts the spreadsheet version cell. Where versionCell is a string that specifies which excel cell the version is in e.g. "B4"
      
      https://github.com/NSLS-II-SST/rsoxs_scans/blob/e167a6a17074df41ab4157a4e2af6adf9e9d074f/rsoxs_scans/spreadsheets.py#L327-L339

**Comment by EliotGann** [comment]
I made the group description change, and smoothed out the wording in general.  unfortunately I'm not sure how to make the version work correctly because we have to write out a sheet with the same version.  when opening a secondary sheet (written by bluesky) we have to have it work still...  I'm not sure how to implement this yet.  perhaps it's changing the writer to also write out the version in a separate sheet.. maybe there is a metadata place in excel files where we can put it.

**Comment by EliotGann** [comment]
ok, I figured out the versioning.  I stash it in the metadata of the file rather than a certain cell.  I can always stash it there in output files as well, so it's all good.

**Comment by EliotGann** [comment]
I'm going to go ahead and merge in an hour or so, unless there are any last minute things

**Pull request merged**
